-- CRIANDO O BANCO DE DADOS 
CREATE DATABASE GESTAOPUBLICA;
GO

USE GESTAOPUBLICA;
GO

-- TEBELA DE CIDADÃOS
CREATE TABLE CIDADAOS (
	CIDADAOID INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	CPF CHAR(11) UNIQUE NOT NULL,
	DATANASCIMENTO DATE NOT NULL,
	ENDERECO VARCHAR(255),
	TELEFONE VARCHAR(20),
	EMAIL VARCHAR(100)
	);

	-- TABELA DE ORGÃOS GOVERNAMENTAIS
CREATE TABLE ORGAOGOVERNAMENTAIS (
	ORGAOID INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(150) NOT NULL,
	SIGLA VARCHAR(10) UNIQUE NOT NULL,
	ENDERECO VARCHAR(255),
	TELEFONE VARCHAR(20)
);


-- TABELA DE SERVIDORES PUBLICOS
CREATE TABLE SERVIDORESPUBLICOS (
    SERVIDORID INT IDENTITY(1,1) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CPF CHAR(11) UNIQUE NOT NULL,
    CARGO VARCHAR(50) NOT NULL,
    SALARIO DECIMAL(10,2) NOT NULL,
    ORGAOID INT NOT NULL,
    CONSTRAINT FK_ORGAO FOREIGN KEY (ORGAOID) REFERENCES ORGAOGOVERNAMENTAIS(ORGAOID)
);

-- TABELA DE ATENDIMENTOS
CREATE TABLE ATENDIMENTOS (
	ATENDIMENTOS INT IDENTITY(1,1) PRIMARY KEY,
	CIDADAOID INT NOT NULL,
	SERVIDORID INT NOT NULL,
	DATAATENDIMENTO DATETIME DEFAULT GETDATE(),
	DESCRICAO TEXT NOT NULL,
	FOREIGN KEY (CIDADAOID) REFERENCES CIDADAOS(CIDADAOID),
	FOREIGN KEY (SERVIDORID) REFERENCES SERVIDORESPUBLICOS(SERVIDORID)
);


-- INSERINDO DADOS NA TABELA CIDADAOS
INSERT INTO CIDADAOS (NOME , CPF, DATANASCIMENTO, ENDERECO, TELEFONE, EMAIL)
VALUES ('JOAO SILVA', '12345678901', '1985-06-15', 'RUA A, 123 - SP','11999999999', 'JOAO.SILVA@EMAIL.COM'),
	   ('MARIA SOUZA', '98765432100', '1990-04-22', 'RUA B, 456 - RJ', '21988888888', 'MARIA.SOUZA@EMAIL.COM');

SELECT * FROM CIDADAOS;

-- INSERINDO DADOS NA TABELA ORGAOGOVERNAMENTAIS
INSERT INTO ORGAOGOVERNAMENTAIS (NOME, SIGLA, ENDERECO, TELEFONE)
VALUES ('MINISTÉRIO DA SAÚDE', 'MS', 'ESPLANADA DOS MINISTÉRIOS, BLOCO G - DF', '6135555555'),
	   ('MINISTÉRIO DA EDUCAÇÃO', 'MEC', 'ESPLANADA DOS MINISTÉRIOS, BOCO L - DF', '6136666666');

SELECT * FROM ORGAOGOVERNAMENTAIS;

-- INSERINDO DADOS NA TABELA SERVIDORESPUBLICOS
INSERT INTO SERVIDORESPUBLICOS (NOME, CPF, CARGO, SALARIO, ORGAOID)
VALUES ('CARLOS ALMEIDA', '11122233344', 'ANALISTA', 7000.00, 1),
	   ('FERNANDA LIMA', '55566677788', 'TÉCNICO ADMINISTRATIVO', 4500.00, 2);

SELECT * FROM SERVIDORESPUBLICOS;


-- INSERINDO DADOS NA TABELA ATENDIMENTOS
INSERT INTO ATENDIMENTOS (CIDADAOID, SERVIDORID, DATAATENDIMENTO, DESCRICAO)
VALUES (1,1, '2025-04-03 10:00:00', 'SOLICITAÇÃO DE ATENDIMENTO MÉDICO'),
	   (2,2, '2025-04-03 11:30:00', 'PEDIDO DE BOLSA DE ESTUDOS.');

SELECT * FROM ATENDIMENTOS;


-- CRIANDO UMA PROCEDURE PARA ADICIONAR UM NOVO ATENDIMENTO

CREATE PROCEDURE ADICIONARATENDIMENTO
	@CIDADAOID INT,
	@SERVIDORID INT,
	@DESCRICAO TEXT
AS
BEGIN
	INSERT INTO ATENDIMENTOS (CIDADAOID, SERVIDORID, DATAATENDIMENTO, DESCRICAO)
	VALUES (@CIDADAOID, @SERVIDORID, GETDATE(), @DESCRICAO);
END;
GO

-- CRIANDO UMA VIEW PARA VISUALIZAR ATENDIMENTO COM INFORMAÇÕES DETALHADAS
CREATE VIEW VW_ATENDIMENTOSDETALHADOS AS
SELECT A.ATENDIMENTOID, C.NOME AS NOMECIDADAO, S.NOME AS NOMESERVIDOR, O.NOME AS NOMEORGAO,
	   A.DATAATENDIMENTO, A.DESCRICAO
FROM ATENDIMENTOS A
JOIN CIDADAOS C ON A.CIDADAOID = C.CIDADAOID
JOIN SERVIDORESPUBLICOS S ON A.SERVIDORID = S.SERVIDORID
JOIN ORGAOGOVERNAMENTAIS O ON S.ORGAOID = O.ORGAOID;
GO
